version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: munirapp/express-standard-api

  web:
    image: munirapp/express-standard-api
    container_name: express-api
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    command: bash -c "npm run build && npm run prod"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: standard-api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: arcs-material
    ports:
      - "8080:8080"
