name: Express Standard API Actions

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
    steps:
      - uses: actions/checkout@v2
      - name: Run Docker Environment
        run: |
          docker-compose build
          docker-compose up -d
      - name: Run Jest Testing
        run: |
          docker exec -t express-api /bin/bash
          npm run test
      - name: Run migration table
        run: |
          docker exec -t express-api /bin/bash
          bash migrate.sh
